### ISSUE TITLE
page/about

### ISSUE THREAD

**Issue by Pandaphobic** [Pandaphobic/mid-heavy-main#36]
Copy over the about page to a Page Parent Component

**Comment by MacMenard** [comment]
![image](https://user-images.githubusercontent.com/73482519/133932894-df25bf14-559c-4bf8-876b-fd27e032d8c8.png)

**Comment by MacMenard** [comment]
- looking in to centering 
- looking in to removing transparent border around about us container 
- make learn more button "green" to follow pattern with contact us page with its button's being blue

**Comment by MillieGrey** [comment]
https://www.w3.org/TR/css-scroll-snap-1/#scroll-snap-type
https://css-tricks.com/practical-css-scroll-snapping/
scroll snapping docs

**Comment by MacMenard** [comment]
closing issue as there's multiple
