### ISSUE TITLE
Footer/add discord logo plz!! 

### ISSUE THREAD

**Issue by MacMenard** [Pandaphobic/mid-heavy-main#55]

**Comment by princerori** [comment]
wanna shoot me the link that the logo should link to please? I can add it to the footer no problem

**Comment by MacMenard** [comment]
Give me a day and ill have a link TYTY!

**Comment by princerori** [comment]
no problem! sounds good, thanks (:

**Comment by MacMenard** [comment]
@princerori Here's the link https://discord.gg/e9mFvZ3W
there's not much to the discord but ill have to build that out

**Comment by princerori** [comment]
just did it and pushed it to main! I also noticed that the footer had gotten behind the particle js so I moved it forward, too.
not totally happy with the logo options I had for discord, but that should be alright.
