### ISSUE TITLE
Backgrounds and Race Conditions

### ISSUE THREAD

**Issue by Pandaphobic** [Pandaphobic/mid-heavy-main#89]
The current impl of our team page makes it so that the backgrounds are decided upon arbitrarily while the data coming in 'could' lead to different results. Here is what is currently happening:

4 gh api calls get fired
they resolve when they are done, with no garantee of order (race condition)
each time one is successfully fetched, they are appended to an array
once the number of team members and the number of data objects in the array is the same, call render
the problem is that there is nothing here specifying the order. 

We have a dice roll of who gets what wallpaper and what order the buttons at the top print our names (in the nav portion of the team page)

**Comment by MillieGrey** [comment]
sorted the members alphabetically by their logins after the api call.
at least now the array isn't random. we'll fix which wallpaper goes where when we hook up unsplash after these couple merges
